### ISSUE TITLE
AutoPaginate error with Laravel 5.5

### ISSUE THREAD

**Issue by asivaneswaran** [maikealame/laravel-auto#13]
There is an error now on the file: `AutoPaginateBlade.php` on line 54.

This is the error: 
```
Caused by
BadMethodCallException: Method appends does not exist.
```

Thanks,

**Comment by maikealame** [comment]
Hi, I'm testing now with 5.5 and no errors. Send me more details controller/view, verify the directive @autopages($objects) if passing a pagination object obtained from autoPaginate().
Get the new 0.4.5.2 to try avoid this error.

**Comment by asivaneswaran** [comment]
Hi,

I see that $param[0] is a collection and there is no method `->appends()`. Is it supposed to be `push()`?

I get the error when I run my phpunit tests and I think it's when I have 0 elements on $param[0].

**Comment by maikealame** [comment]
Ok, the problem is it. You can not paginate with collections, follow code above:
```
Auto::onlyTrashed();
$tickets = \App\Ticket::select("ticket.*")
            ->join('portfolio', 'ticket.portfolio_id', '=', 'portfolio.id')
            ->autoWhere()->autoSort()->autoPaginate();
dd($tickets);
```
Result:
```
LengthAwarePaginator {#209 ▼
  #total: 0
  #lastPage: 1
  #items: Collection {#211 ▼
    #items: []
  }
  #perPage: 10
  #currentPage: 1
  #path: "http://laravel55.localhost/test/autowhere"
  #query: []
  #fragment: null
  #pageName: "page"
}
```

When test the append exists:
`dd(method_exists($tickets,"appends"));`
Result:
`true`

My `LengthAwarePaginator` object has a collection empty like you get, but appends not exists in collection, just in `LengthAwarePaginator`. If you not pass this object type in `@autopages()` the $param[0] will be wrong.

**Comment by asivaneswaran** [comment]
Oh alright. So when the query was empty, I was doing a `return collect[]` but now I do: `return new Paginator([], 10);`

Thank you
