### ISSUE TITLE
@autowherefilter for range of date

### ISSUE THREAD

**Issue by AndreySavenkov** [maikealame/laravel-auto#16]
Good day!

Is there some example of how to use **@autowherefilter** for date range filtering?
Or maybe it is possible to implement this functionality?

Thanks in advance.

**Comment by maikealame** [comment]
Hi

So... this is a big problem I got early in a project ! 
it's because I'm not considering layouts in this package. See what can be done:

- Range in one column:

`http://localhost/usuarios?filter[birth]=12/12/1990|12/12/2000`

it can be made by manually input a value like this url ( start|end ) in a input name="birth", or if using a plugin see if can be changed after click function because some plugins block the manually input:
`https://eonasdan.github.io/bootstrap-datetimepicker/Options/#keepinvalid`
I used this plugin many times and it can be done with this option, when you click in some date this generate a day string to value of input and it can be manually changed to other value with the end date too by user input.

- Range in many columns:

Sometimes you need a complex search like in calendar that has many matches dates possibilities. I used this like below:

```
TicketAttendance::whereRaw(
                Auto::where()->class(TicketAttendance::class)
                    ->columns(["start|end"=>"between_columns_date"])
                    ->or(["start","end"])
                    ->render($where)
            )->autoSort()->autoPaginate();
```
Can be simplified in:
```
TicketAttendance::Autowhere([
                    'columns' => ["start|end"=>"between_columns_date"],
                    'or' => ["start","end"]
            )->autoSort()->autoPaginate();
```
That "between_columns_date" is new feature and not can be found in docs yet. Just put a input with name "start|end" or other name you wish and this do everything.

---

Otherwise, if a event after click and before search processing can help you, it can be made. Or maybe a new blade directive like @authowherebetween but send me a print of layout to give me a inspiration.

**Comment by AndreySavenkov** [comment]
i think this layout will help understand

```
<th>
    <div class="input-group-content" >
        <input type="text" class="form-control datepicker input-filter" data-date-autoclose="true" data-date-today-highlight="true" data-date-format="yyyy-mm-dd" data-date-language="ru" name="contract_sign_date__greatorequal">
    </div>
    <span class="input-group-addon"> - </span>
    <div class="input-group-content">
        <input type="text" class="form-control datepicker input-filter" data-date-autoclose="true" data-date-today-highlight="true" data-date-format="yyyy-mm-dd" data-date-language="ru" name="contract_sign_date__lessorequal">
    </div>
</th>

```

and SQL WHERE should look like:
`SELECT * FROM contracts WHERE (contract_sign_date >= '2018-01-01' AND contract_sign_date <= '2018-02-02')`

**Comment by AndreySavenkov** [comment]
You've got something similar to this on 3rd screenshot in README, but this is not in table header

**Comment by AndreySavenkov** [comment]
finally i've made this :)

```html
<th>
    <input type="text" style="display: none;" class="input-filter" name="contract_sign_date" id="contract_sign_date" value="@autowherefilter('contract_sign_date')">
    <div class="input-group-content" >
        <input type="text" class="form-control datepicker contract_sign_date" data-date-autoclose="true" data-date-today-highlight="true" data-date-format="yyyy-mm-dd" data-date-language="ru" id="contract_sign_date__greatorequal">
    </div>
    <span class="input-group-addon"> &mdash; </span>
    <div class="input-group-content">
        <input type="text" class="form-control datepicker contract_sign_date" data-date-autoclose="true" data-date-today-highlight="true" data-date-format="yyyy-mm-dd" data-date-language="ru" id="contract_sign_date__lessorequal">
    </div>
</th>
```

in layout = first input field is not visible,  and value is generated by onchange event of two input fields:
```javascript
$(".contract_sign_date").on("change", function() {
    let startdate = $('#contract_sign_date__greatorequal').val();
    let enddate = $('#contract_sign_date__lessorequal').val();
    let querystart, queryend;
    if (startdate !== '') {
        querystart = startdate;
    } else {
        querystart = "*";
    }
    if (enddate !== '') {
        queryend = enddate;
    } else {
        queryend = "*";
    }
    let query = querystart + "|" + queryend;
    $("#contract_sign_date").val(query);
});
```

and on page load it parses the value of filter (hidden input field) and sets values of both date input fields:
```javascript
$(function () {
    if ($("#contract_sign_date").val() !== '') {
        let vals = $("#contract_sign_date").val().split("|");
        if (vals[0] !== '*') {
            $('#contract_sign_date__greatorequal').datepicker("update", vals[0]);
        }
        if (vals[1] !== '*') {
            $('#contract_sign_date__lessorequal').datepicker("update", vals[1]);
        }
    }
});
```

**Comment by AndreySavenkov** [comment]
please, add some kind of this to documentation

**Comment by maikealame** [comment]
Thanks @in7rude 

This will improve, now I need to see how this can be done without interfering layout. Probably with input hidden like yours.
